name: Self-Hosted CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log Node.js version
      run: node --version

    - name: Log available disk space
      shell: pwsh
      run: |
        Write-Output "Checking available disk space:"
        Get-PSDrive -PSProvider 'FileSystem' | Select-Object Name, Used, Free

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test -- --watch=false --browsers=ChromeHeadless --no-progress
